export const ENV_VARS = {
  PORT: 'PORT',
  JWT_SECRET: 'JWT_SECRET',
  FRONTEND_HOST: 'FRONTEND_HOST',
  SMTP_PORT: 'SMTP_PORT',
  SMTP_HOST: 'SMTP_HOST',
  SMTP_USERNAME: 'SMTP_USERNAME',
  SMTP_PASSWORD: 'SMTP_PASSWORD',
  SMTP_FROM: 'SMTP_FROM',
};

export const MONGO_DB_VARS = {
  MONGO_USER: 'MONGO_USER',
  MONGO_PASSWORLD: 'MONGO_PASSWORLD',
  MONGODB_URL: 'MONGODB_URL',
  MONGODB_DB: 'MONGODB_DB',
};
